//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MyDBModel", "FK_Article_0_0", "Establishment", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Migration.Establishment), "Article", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Migration.Article), true)]
[assembly: EdmRelationshipAttribute("MyDBModel", "FK_Reservation_4_0", "Article", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Migration.Article), "Reservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Migration.Reservation), true)]
[assembly: EdmRelationshipAttribute("MyDBModel", "FK_Credit_0_0", "Establishment", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Migration.Establishment), "Credit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Migration.Credit), true)]
[assembly: EdmRelationshipAttribute("MyDBModel", "FK_Reservation_2_0", "Establishment", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Migration.Establishment), "Reservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Migration.Reservation), true)]
[assembly: EdmRelationshipAttribute("MyDBModel", "FK_Reservation_3_0", "Establishment", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Migration.Establishment), "Reservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Migration.Reservation), true)]
[assembly: EdmRelationshipAttribute("MyDBModel", "FK_Users_0_0", "Establishment", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Migration.Establishment), "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Migration.Users), true)]
[assembly: EdmRelationshipAttribute("MyDBModel", "FK_Vente_0_0", "Establishment", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Migration.Establishment), "Vente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Migration.Vente), true)]
[assembly: EdmRelationshipAttribute("MyDBModel", "FK_Reservation_0_0", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Migration.Users), "Reservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Migration.Reservation), true)]
[assembly: EdmRelationshipAttribute("MyDBModel", "FK_Reservation_1_0", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Migration.Users), "Reservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Migration.Reservation), true)]

#endregion

namespace Migration
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MyDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MyDBEntities object using the connection string found in the 'MyDBEntities' section of the application configuration file.
        /// </summary>
        public MyDBEntities() : base("name=MyDBEntities", "MyDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyDBEntities object.
        /// </summary>
        public MyDBEntities(string connectionString) : base(connectionString, "MyDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyDBEntities object.
        /// </summary>
        public MyDBEntities(EntityConnection connection) : base(connection, "MyDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Article> Article
        {
            get
            {
                if ((_Article == null))
                {
                    _Article = base.CreateObjectSet<Article>("Article");
                }
                return _Article;
            }
        }
        private ObjectSet<Article> _Article;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Credit> Credit
        {
            get
            {
                if ((_Credit == null))
                {
                    _Credit = base.CreateObjectSet<Credit>("Credit");
                }
                return _Credit;
            }
        }
        private ObjectSet<Credit> _Credit;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Establishment> Establishment
        {
            get
            {
                if ((_Establishment == null))
                {
                    _Establishment = base.CreateObjectSet<Establishment>("Establishment");
                }
                return _Establishment;
            }
        }
        private ObjectSet<Establishment> _Establishment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reservation> Reservation
        {
            get
            {
                if ((_Reservation == null))
                {
                    _Reservation = base.CreateObjectSet<Reservation>("Reservation");
                }
                return _Reservation;
            }
        }
        private ObjectSet<Reservation> _Reservation;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vente> Vente
        {
            get
            {
                if ((_Vente == null))
                {
                    _Vente = base.CreateObjectSet<Vente>("Vente");
                }
                return _Vente;
            }
        }
        private ObjectSet<Vente> _Vente;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Article EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticle(Article article)
        {
            base.AddObject("Article", article);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Credit EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCredit(Credit credit)
        {
            base.AddObject("Credit", credit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Establishment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEstablishment(Establishment establishment)
        {
            base.AddObject("Establishment", establishment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reservation EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReservation(Reservation reservation)
        {
            base.AddObject("Reservation", reservation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVente(Vente vente)
        {
            base.AddObject("Vente", vente);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyDBModel", Name="Article")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Article : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Article object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="designation">Initial value of the Designation property.</param>
        /// <param name="prixAchat">Initial value of the PrixAchat property.</param>
        /// <param name="prixVente">Initial value of the PrixVente property.</param>
        /// <param name="qT">Initial value of the QT property.</param>
        /// <param name="isGenerique">Initial value of the IsGenerique property.</param>
        public static Article CreateArticle(global::System.Int64 id, global::System.String designation, global::System.Decimal prixAchat, global::System.Decimal prixVente, global::System.Int32 qT, global::System.Boolean isGenerique)
        {
            Article article = new Article();
            article.ID = id;
            article.Designation = designation;
            article.PrixAchat = prixAchat;
            article.PrixVente = prixVente;
            article.QT = qT;
            article.IsGenerique = isGenerique;
            return article;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Designation
        {
            get
            {
                return _Designation;
            }
            set
            {
                OnDesignationChanging(value);
                ReportPropertyChanging("Designation");
                _Designation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Designation");
                OnDesignationChanged();
            }
        }
        private global::System.String _Designation;
        partial void OnDesignationChanging(global::System.String value);
        partial void OnDesignationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PrixAchat
        {
            get
            {
                return _PrixAchat;
            }
            set
            {
                OnPrixAchatChanging(value);
                ReportPropertyChanging("PrixAchat");
                _PrixAchat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrixAchat");
                OnPrixAchatChanged();
            }
        }
        private global::System.Decimal _PrixAchat;
        partial void OnPrixAchatChanging(global::System.Decimal value);
        partial void OnPrixAchatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PrixVente
        {
            get
            {
                return _PrixVente;
            }
            set
            {
                OnPrixVenteChanging(value);
                ReportPropertyChanging("PrixVente");
                _PrixVente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrixVente");
                OnPrixVenteChanged();
            }
        }
        private global::System.Decimal _PrixVente;
        partial void OnPrixVenteChanging(global::System.Decimal value);
        partial void OnPrixVenteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SN
        {
            get
            {
                return _SN;
            }
            set
            {
                OnSNChanging(value);
                ReportPropertyChanging("SN");
                _SN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SN");
                OnSNChanged();
            }
        }
        private global::System.String _SN;
        partial void OnSNChanging(global::System.String value);
        partial void OnSNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QT
        {
            get
            {
                return _QT;
            }
            set
            {
                OnQTChanging(value);
                ReportPropertyChanging("QT");
                _QT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QT");
                OnQTChanged();
            }
        }
        private global::System.Int32 _QT;
        partial void OnQTChanging(global::System.Int32 value);
        partial void OnQTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsGenerique
        {
            get
            {
                return _IsGenerique;
            }
            set
            {
                OnIsGeneriqueChanging(value);
                ReportPropertyChanging("IsGenerique");
                _IsGenerique = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsGenerique");
                OnIsGeneriqueChanged();
            }
        }
        private global::System.Boolean _IsGenerique;
        partial void OnIsGeneriqueChanging(global::System.Boolean value);
        partial void OnIsGeneriqueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> EstablishmentId
        {
            get
            {
                return _EstablishmentId;
            }
            set
            {
                OnEstablishmentIdChanging(value);
                ReportPropertyChanging("EstablishmentId");
                _EstablishmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EstablishmentId");
                OnEstablishmentIdChanged();
            }
        }
        private Nullable<global::System.Int64> _EstablishmentId;
        partial void OnEstablishmentIdChanging(Nullable<global::System.Int64> value);
        partial void OnEstablishmentIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Article_0_0", "Establishment")]
        public Establishment Establishment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Article_0_0", "Establishment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Article_0_0", "Establishment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Establishment> EstablishmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Article_0_0", "Establishment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Establishment>("MyDBModel.FK_Article_0_0", "Establishment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Reservation_4_0", "Reservation")]
        public EntityCollection<Reservation> Reservation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reservation>("MyDBModel.FK_Reservation_4_0", "Reservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reservation>("MyDBModel.FK_Reservation_4_0", "Reservation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyDBModel", Name="Credit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Credit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Credit object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Credit CreateCredit(global::System.Int64 id)
        {
            Credit credit = new Credit();
            credit.ID = id;
            return credit;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ArticleId
        {
            get
            {
                return _ArticleId;
            }
            set
            {
                OnArticleIdChanging(value);
                ReportPropertyChanging("ArticleId");
                _ArticleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ArticleId");
                OnArticleIdChanged();
            }
        }
        private Nullable<global::System.Int64> _ArticleId;
        partial void OnArticleIdChanging(Nullable<global::System.Int64> value);
        partial void OnArticleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Designation
        {
            get
            {
                return _Designation;
            }
            set
            {
                OnDesignationChanging(value);
                ReportPropertyChanging("Designation");
                _Designation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Designation");
                OnDesignationChanged();
            }
        }
        private global::System.String _Designation;
        partial void OnDesignationChanging(global::System.String value);
        partial void OnDesignationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrixAchat
        {
            get
            {
                return _PrixAchat;
            }
            set
            {
                OnPrixAchatChanging(value);
                ReportPropertyChanging("PrixAchat");
                _PrixAchat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrixAchat");
                OnPrixAchatChanged();
            }
        }
        private Nullable<global::System.Decimal> _PrixAchat;
        partial void OnPrixAchatChanging(Nullable<global::System.Decimal> value);
        partial void OnPrixAchatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrixVente
        {
            get
            {
                return _PrixVente;
            }
            set
            {
                OnPrixVenteChanging(value);
                ReportPropertyChanging("PrixVente");
                _PrixVente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrixVente");
                OnPrixVenteChanged();
            }
        }
        private Nullable<global::System.Decimal> _PrixVente;
        partial void OnPrixVenteChanging(Nullable<global::System.Decimal> value);
        partial void OnPrixVenteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SN
        {
            get
            {
                return _SN;
            }
            set
            {
                OnSNChanging(value);
                ReportPropertyChanging("SN");
                _SN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SN");
                OnSNChanged();
            }
        }
        private global::System.String _SN;
        partial void OnSNChanging(global::System.String value);
        partial void OnSNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateDeVente
        {
            get
            {
                return _DateDeVente;
            }
            set
            {
                OnDateDeVenteChanging(value);
                ReportPropertyChanging("DateDeVente");
                _DateDeVente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateDeVente");
                OnDateDeVenteChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateDeVente;
        partial void OnDateDeVenteChanging(Nullable<global::System.DateTime> value);
        partial void OnDateDeVenteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QT
        {
            get
            {
                return _QT;
            }
            set
            {
                OnQTChanging(value);
                ReportPropertyChanging("QT");
                _QT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QT");
                OnQTChanged();
            }
        }
        private Nullable<global::System.Int32> _QT;
        partial void OnQTChanging(Nullable<global::System.Int32> value);
        partial void OnQTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomClient
        {
            get
            {
                return _NomClient;
            }
            set
            {
                OnNomClientChanging(value);
                ReportPropertyChanging("NomClient");
                _NomClient = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NomClient");
                OnNomClientChanged();
            }
        }
        private global::System.String _NomClient;
        partial void OnNomClientChanging(global::System.String value);
        partial void OnNomClientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Coordonnes
        {
            get
            {
                return _Coordonnes;
            }
            set
            {
                OnCoordonnesChanging(value);
                ReportPropertyChanging("Coordonnes");
                _Coordonnes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Coordonnes");
                OnCoordonnesChanged();
            }
        }
        private global::System.String _Coordonnes;
        partial void OnCoordonnesChanging(global::System.String value);
        partial void OnCoordonnesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModePaiement
        {
            get
            {
                return _ModePaiement;
            }
            set
            {
                OnModePaiementChanging(value);
                ReportPropertyChanging("ModePaiement");
                _ModePaiement = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ModePaiement");
                OnModePaiementChanged();
            }
        }
        private global::System.String _ModePaiement;
        partial void OnModePaiementChanging(global::System.String value);
        partial void OnModePaiementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int64> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int64> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> EstablishmentId
        {
            get
            {
                return _EstablishmentId;
            }
            set
            {
                OnEstablishmentIdChanging(value);
                ReportPropertyChanging("EstablishmentId");
                _EstablishmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EstablishmentId");
                OnEstablishmentIdChanged();
            }
        }
        private Nullable<global::System.Int64> _EstablishmentId;
        partial void OnEstablishmentIdChanging(Nullable<global::System.Int64> value);
        partial void OnEstablishmentIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Credit_0_0", "Establishment")]
        public Establishment Establishment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Credit_0_0", "Establishment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Credit_0_0", "Establishment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Establishment> EstablishmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Credit_0_0", "Establishment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Establishment>("MyDBModel.FK_Credit_0_0", "Establishment", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyDBModel", Name="Establishment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Establishment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Establishment object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Establishment CreateEstablishment(global::System.Int64 id, global::System.String name)
        {
            Establishment establishment = new Establishment();
            establishment.Id = id;
            establishment.Name = name;
            return establishment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Article_0_0", "Article")]
        public EntityCollection<Article> Article
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Article>("MyDBModel.FK_Article_0_0", "Article");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Article>("MyDBModel.FK_Article_0_0", "Article", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Credit_0_0", "Credit")]
        public EntityCollection<Credit> Credit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Credit>("MyDBModel.FK_Credit_0_0", "Credit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Credit>("MyDBModel.FK_Credit_0_0", "Credit", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Reservation_2_0", "Reservation")]
        public EntityCollection<Reservation> Reservation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reservation>("MyDBModel.FK_Reservation_2_0", "Reservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reservation>("MyDBModel.FK_Reservation_2_0", "Reservation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Reservation_3_0", "Reservation")]
        public EntityCollection<Reservation> Reservation1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reservation>("MyDBModel.FK_Reservation_3_0", "Reservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reservation>("MyDBModel.FK_Reservation_3_0", "Reservation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Users_0_0", "Users")]
        public EntityCollection<Users> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Users>("MyDBModel.FK_Users_0_0", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Users>("MyDBModel.FK_Users_0_0", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Vente_0_0", "Vente")]
        public EntityCollection<Vente> Vente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vente>("MyDBModel.FK_Vente_0_0", "Vente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vente>("MyDBModel.FK_Vente_0_0", "Vente", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyDBModel", Name="Reservation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reservation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Reservation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="articleId">Initial value of the ArticleId property.</param>
        /// <param name="sN">Initial value of the SN property.</param>
        /// <param name="fromId">Initial value of the FromId property.</param>
        /// <param name="toId">Initial value of the ToId property.</param>
        /// <param name="requestDate">Initial value of the RequestDate property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        public static Reservation CreateReservation(global::System.Int64 id, global::System.Int64 articleId, global::System.String sN, global::System.Int64 fromId, global::System.Int64 toId, global::System.DateTime requestDate, global::System.Int64 userId)
        {
            Reservation reservation = new Reservation();
            reservation.Id = id;
            reservation.ArticleId = articleId;
            reservation.SN = sN;
            reservation.FromId = fromId;
            reservation.ToId = toId;
            reservation.RequestDate = requestDate;
            reservation.UserId = userId;
            return reservation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ArticleId
        {
            get
            {
                return _ArticleId;
            }
            set
            {
                OnArticleIdChanging(value);
                ReportPropertyChanging("ArticleId");
                _ArticleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ArticleId");
                OnArticleIdChanged();
            }
        }
        private global::System.Int64 _ArticleId;
        partial void OnArticleIdChanging(global::System.Int64 value);
        partial void OnArticleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SN
        {
            get
            {
                return _SN;
            }
            set
            {
                OnSNChanging(value);
                ReportPropertyChanging("SN");
                _SN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SN");
                OnSNChanged();
            }
        }
        private global::System.String _SN;
        partial void OnSNChanging(global::System.String value);
        partial void OnSNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FromId
        {
            get
            {
                return _FromId;
            }
            set
            {
                OnFromIdChanging(value);
                ReportPropertyChanging("FromId");
                _FromId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FromId");
                OnFromIdChanged();
            }
        }
        private global::System.Int64 _FromId;
        partial void OnFromIdChanging(global::System.Int64 value);
        partial void OnFromIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ToId
        {
            get
            {
                return _ToId;
            }
            set
            {
                OnToIdChanging(value);
                ReportPropertyChanging("ToId");
                _ToId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ToId");
                OnToIdChanged();
            }
        }
        private global::System.Int64 _ToId;
        partial void OnToIdChanging(global::System.Int64 value);
        partial void OnToIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RequestDate
        {
            get
            {
                return _RequestDate;
            }
            set
            {
                OnRequestDateChanging(value);
                ReportPropertyChanging("RequestDate");
                _RequestDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RequestDate");
                OnRequestDateChanged();
            }
        }
        private global::System.DateTime _RequestDate;
        partial void OnRequestDateChanging(global::System.DateTime value);
        partial void OnRequestDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsValidated
        {
            get
            {
                return _IsValidated;
            }
            set
            {
                OnIsValidatedChanging(value);
                ReportPropertyChanging("IsValidated");
                _IsValidated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsValidated");
                OnIsValidatedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsValidated;
        partial void OnIsValidatedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsValidatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ValidationDate
        {
            get
            {
                return _ValidationDate;
            }
            set
            {
                OnValidationDateChanging(value);
                ReportPropertyChanging("ValidationDate");
                _ValidationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValidationDate");
                OnValidationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ValidationDate;
        partial void OnValidationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnValidationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ValidatedBy
        {
            get
            {
                return _ValidatedBy;
            }
            set
            {
                OnValidatedByChanging(value);
                ReportPropertyChanging("ValidatedBy");
                _ValidatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValidatedBy");
                OnValidatedByChanged();
            }
        }
        private Nullable<global::System.Int64> _ValidatedBy;
        partial void OnValidatedByChanging(Nullable<global::System.Int64> value);
        partial void OnValidatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Qt
        {
            get
            {
                return _Qt;
            }
            set
            {
                OnQtChanging(value);
                ReportPropertyChanging("Qt");
                _Qt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Qt");
                OnQtChanged();
            }
        }
        private Nullable<global::System.Int32> _Qt;
        partial void OnQtChanging(Nullable<global::System.Int32> value);
        partial void OnQtChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Reservation_4_0", "Article")]
        public Article Article
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Article>("MyDBModel.FK_Reservation_4_0", "Article").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Article>("MyDBModel.FK_Reservation_4_0", "Article").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Article> ArticleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Article>("MyDBModel.FK_Reservation_4_0", "Article");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Article>("MyDBModel.FK_Reservation_4_0", "Article", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Reservation_2_0", "Establishment")]
        public Establishment Establishment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Reservation_2_0", "Establishment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Reservation_2_0", "Establishment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Establishment> EstablishmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Reservation_2_0", "Establishment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Establishment>("MyDBModel.FK_Reservation_2_0", "Establishment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Reservation_3_0", "Establishment")]
        public Establishment Establishment1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Reservation_3_0", "Establishment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Reservation_3_0", "Establishment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Establishment> Establishment1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Reservation_3_0", "Establishment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Establishment>("MyDBModel.FK_Reservation_3_0", "Establishment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Reservation_0_0", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("MyDBModel.FK_Reservation_0_0", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("MyDBModel.FK_Reservation_0_0", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("MyDBModel.FK_Reservation_0_0", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("MyDBModel.FK_Reservation_0_0", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Reservation_1_0", "Users")]
        public Users Users1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("MyDBModel.FK_Reservation_1_0", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("MyDBModel.FK_Reservation_1_0", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> Users1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("MyDBModel.FK_Reservation_1_0", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("MyDBModel.FK_Reservation_1_0", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyDBModel", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Users CreateUsers(global::System.Int64 id)
        {
            Users users = new Users();
            users.Id = id;
            return users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pass
        {
            get
            {
                return _Pass;
            }
            set
            {
                OnPassChanging(value);
                ReportPropertyChanging("Pass");
                _Pass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pass");
                OnPassChanged();
            }
        }
        private global::System.String _Pass;
        partial void OnPassChanging(global::System.String value);
        partial void OnPassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Stock
        {
            get
            {
                return _Stock;
            }
            set
            {
                OnStockChanging(value);
                ReportPropertyChanging("Stock");
                _Stock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stock");
                OnStockChanged();
            }
        }
        private Nullable<global::System.Boolean> _Stock;
        partial void OnStockChanging(Nullable<global::System.Boolean> value);
        partial void OnStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Vente
        {
            get
            {
                return _Vente;
            }
            set
            {
                OnVenteChanging(value);
                ReportPropertyChanging("Vente");
                _Vente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vente");
                OnVenteChanged();
            }
        }
        private Nullable<global::System.Boolean> _Vente;
        partial void OnVenteChanging(Nullable<global::System.Boolean> value);
        partial void OnVenteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Vente_S
        {
            get
            {
                return _Vente_S;
            }
            set
            {
                OnVente_SChanging(value);
                ReportPropertyChanging("Vente_S");
                _Vente_S = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vente_S");
                OnVente_SChanged();
            }
        }
        private Nullable<global::System.Boolean> _Vente_S;
        partial void OnVente_SChanging(Nullable<global::System.Boolean> value);
        partial void OnVente_SChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> HistoriqueVente
        {
            get
            {
                return _HistoriqueVente;
            }
            set
            {
                OnHistoriqueVenteChanging(value);
                ReportPropertyChanging("HistoriqueVente");
                _HistoriqueVente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HistoriqueVente");
                OnHistoriqueVenteChanged();
            }
        }
        private Nullable<global::System.Boolean> _HistoriqueVente;
        partial void OnHistoriqueVenteChanging(Nullable<global::System.Boolean> value);
        partial void OnHistoriqueVenteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AVoir
        {
            get
            {
                return _AVoir;
            }
            set
            {
                OnAVoirChanging(value);
                ReportPropertyChanging("AVoir");
                _AVoir = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AVoir");
                OnAVoirChanged();
            }
        }
        private Nullable<global::System.Boolean> _AVoir;
        partial void OnAVoirChanging(Nullable<global::System.Boolean> value);
        partial void OnAVoirChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Inventaire
        {
            get
            {
                return _Inventaire;
            }
            set
            {
                OnInventaireChanging(value);
                ReportPropertyChanging("Inventaire");
                _Inventaire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Inventaire");
                OnInventaireChanged();
            }
        }
        private Nullable<global::System.Boolean> _Inventaire;
        partial void OnInventaireChanging(Nullable<global::System.Boolean> value);
        partial void OnInventaireChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> VenteCredit
        {
            get
            {
                return _VenteCredit;
            }
            set
            {
                OnVenteCreditChanging(value);
                ReportPropertyChanging("VenteCredit");
                _VenteCredit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VenteCredit");
                OnVenteCreditChanged();
            }
        }
        private Nullable<global::System.Boolean> _VenteCredit;
        partial void OnVenteCreditChanging(Nullable<global::System.Boolean> value);
        partial void OnVenteCreditChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> VenteCredit_S
        {
            get
            {
                return _VenteCredit_S;
            }
            set
            {
                OnVenteCredit_SChanging(value);
                ReportPropertyChanging("VenteCredit_S");
                _VenteCredit_S = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VenteCredit_S");
                OnVenteCredit_SChanged();
            }
        }
        private Nullable<global::System.Boolean> _VenteCredit_S;
        partial void OnVenteCredit_SChanging(Nullable<global::System.Boolean> value);
        partial void OnVenteCredit_SChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> GererAcces
        {
            get
            {
                return _GererAcces;
            }
            set
            {
                OnGererAccesChanging(value);
                ReportPropertyChanging("GererAcces");
                _GererAcces = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GererAcces");
                OnGererAccesChanged();
            }
        }
        private Nullable<global::System.Boolean> _GererAcces;
        partial void OnGererAccesChanging(Nullable<global::System.Boolean> value);
        partial void OnGererAccesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ViderBase
        {
            get
            {
                return _ViderBase;
            }
            set
            {
                OnViderBaseChanging(value);
                ReportPropertyChanging("ViderBase");
                _ViderBase = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ViderBase");
                OnViderBaseChanged();
            }
        }
        private Nullable<global::System.Boolean> _ViderBase;
        partial void OnViderBaseChanging(Nullable<global::System.Boolean> value);
        partial void OnViderBaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> EstablishmentId
        {
            get
            {
                return _EstablishmentId;
            }
            set
            {
                OnEstablishmentIdChanging(value);
                ReportPropertyChanging("EstablishmentId");
                _EstablishmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EstablishmentId");
                OnEstablishmentIdChanged();
            }
        }
        private Nullable<global::System.Int64> _EstablishmentId;
        partial void OnEstablishmentIdChanging(Nullable<global::System.Int64> value);
        partial void OnEstablishmentIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Users_0_0", "Establishment")]
        public Establishment Establishment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Users_0_0", "Establishment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Users_0_0", "Establishment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Establishment> EstablishmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Users_0_0", "Establishment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Establishment>("MyDBModel.FK_Users_0_0", "Establishment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Reservation_0_0", "Reservation")]
        public EntityCollection<Reservation> Reservation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reservation>("MyDBModel.FK_Reservation_0_0", "Reservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reservation>("MyDBModel.FK_Reservation_0_0", "Reservation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Reservation_1_0", "Reservation")]
        public EntityCollection<Reservation> Reservation1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reservation>("MyDBModel.FK_Reservation_1_0", "Reservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reservation>("MyDBModel.FK_Reservation_1_0", "Reservation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyDBModel", Name="Vente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vente object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Vente CreateVente(global::System.Int64 id)
        {
            Vente vente = new Vente();
            vente.ID = id;
            return vente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ArticleId
        {
            get
            {
                return _ArticleId;
            }
            set
            {
                OnArticleIdChanging(value);
                ReportPropertyChanging("ArticleId");
                _ArticleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ArticleId");
                OnArticleIdChanged();
            }
        }
        private Nullable<global::System.Int64> _ArticleId;
        partial void OnArticleIdChanging(Nullable<global::System.Int64> value);
        partial void OnArticleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Designation
        {
            get
            {
                return _Designation;
            }
            set
            {
                OnDesignationChanging(value);
                ReportPropertyChanging("Designation");
                _Designation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Designation");
                OnDesignationChanged();
            }
        }
        private global::System.String _Designation;
        partial void OnDesignationChanging(global::System.String value);
        partial void OnDesignationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrixAchat
        {
            get
            {
                return _PrixAchat;
            }
            set
            {
                OnPrixAchatChanging(value);
                ReportPropertyChanging("PrixAchat");
                _PrixAchat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrixAchat");
                OnPrixAchatChanged();
            }
        }
        private Nullable<global::System.Decimal> _PrixAchat;
        partial void OnPrixAchatChanging(Nullable<global::System.Decimal> value);
        partial void OnPrixAchatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrixVente
        {
            get
            {
                return _PrixVente;
            }
            set
            {
                OnPrixVenteChanging(value);
                ReportPropertyChanging("PrixVente");
                _PrixVente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrixVente");
                OnPrixVenteChanged();
            }
        }
        private Nullable<global::System.Decimal> _PrixVente;
        partial void OnPrixVenteChanging(Nullable<global::System.Decimal> value);
        partial void OnPrixVenteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SN
        {
            get
            {
                return _SN;
            }
            set
            {
                OnSNChanging(value);
                ReportPropertyChanging("SN");
                _SN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SN");
                OnSNChanged();
            }
        }
        private global::System.String _SN;
        partial void OnSNChanging(global::System.String value);
        partial void OnSNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateDeVente
        {
            get
            {
                return _DateDeVente;
            }
            set
            {
                OnDateDeVenteChanging(value);
                ReportPropertyChanging("DateDeVente");
                _DateDeVente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateDeVente");
                OnDateDeVenteChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateDeVente;
        partial void OnDateDeVenteChanging(Nullable<global::System.DateTime> value);
        partial void OnDateDeVenteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QT
        {
            get
            {
                return _QT;
            }
            set
            {
                OnQTChanging(value);
                ReportPropertyChanging("QT");
                _QT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QT");
                OnQTChanged();
            }
        }
        private Nullable<global::System.Int32> _QT;
        partial void OnQTChanging(Nullable<global::System.Int32> value);
        partial void OnQTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> EstablishmentId
        {
            get
            {
                return _EstablishmentId;
            }
            set
            {
                OnEstablishmentIdChanging(value);
                ReportPropertyChanging("EstablishmentId");
                _EstablishmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EstablishmentId");
                OnEstablishmentIdChanged();
            }
        }
        private Nullable<global::System.Int64> _EstablishmentId;
        partial void OnEstablishmentIdChanging(Nullable<global::System.Int64> value);
        partial void OnEstablishmentIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyDBModel", "FK_Vente_0_0", "Establishment")]
        public Establishment Establishment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Vente_0_0", "Establishment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Vente_0_0", "Establishment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Establishment> EstablishmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establishment>("MyDBModel.FK_Vente_0_0", "Establishment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Establishment>("MyDBModel.FK_Vente_0_0", "Establishment", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
